### ISSUE TITLE
formatting failed solution

### ISSUE THREAD

**Issue by jackal1988** [affenwiesel/matlab-formatter-vscode#28]
Hi, if anyone have ever bumped into "formatting failed" problem like this:
![problem](https://user-images.githubusercontent.com/4718024/54412133-95457100-472c-11e9-9158-059c91d92651.png)
You may try to add your `python.exe`path into your system path like this:
![solution-matlab-format](https://user-images.githubusercontent.com/4718024/54412291-1dc41180-472d-11e9-8a4b-51295d61fb15.png)

maybe in the future,  the python path can be tunable? @affenwiesel  thanks, anyway~

**Comment by VictoriousRaptor** [comment]
I already have that entry in my system PATH, but it still doesn't work. It seems that if a file includes Chinese comments (in **UTF-8 encoding**), then 'formatting failed' notation pops up.
I've tried running the script and ran into the same error.

> Traceback (most recent call last):
  File "matlab_formatter.py", line 280, in <module>
    main()
  File "matlab_formatter.py", line 277, in main
    formatter.formatFile(sys.argv[1], start, end)
  File "matlab_formatter.py", line 212, in formatFile
    rlines = f.readlines()[start-1:end]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb0 in position 102: illegal multibyte sequence

The file being read is actually in UTF-8 encoding but decoded in gbk somehow.

**Comment by VictoriousRaptor** [comment]
Fixed in #30 .

**Comment by Hootrix** [comment]
If the file is gbk encoded, it will not work.
GBK文件也是不能使用的

```
Traceback (most recent call last):
  File "/Users/panc/.vscode/extensions/affenwiesel.matlab-formatter-2.4.12/formatter/matlab_formatter.py", line 300, in <module>
    main()
  File "/Users/panc/.vscode/extensions/affenwiesel.matlab-formatter-2.4.12/formatter/matlab_formatter.py", line 297, in main
    formatter.formatFile(sys.argv[1], start, end)
  File "/Users/panc/.vscode/extensions/affenwiesel.matlab-formatter-2.4.12/formatter/matlab_formatter.py", line 232, in formatFile
    rlines = f.readlines()[start - 1:end]
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 4: invalid continuation byte
```

**Comment by affenwiesel** [comment]
Please let me know if it works now.

**Comment by ilcpm** [comment]
both `utf-8` and `GBK` with Chinese can be will formatted now
(last issue was closed by me, so i reply in this issue😂)

**Comment by affenwiesel** [comment]
> i wonder how you did this without provide the file code by user,
> did you get this from VSC itself?

To be honest, this kind of happened by accident ;)
