### ISSUE TITLE
multiple function out arguments with no spaces

### ISSUE THREAD

**Issue by jorabold** [affenwiesel/matlab-formatter-vscode#45]
Trying to format
```matlab
function[foo1, foo2]=myFun(a,b,c)
```
results in crash
```sh
matlab-formatter-vscode\formatter>python matlab_formatter.py test.m
Traceback (most recent call last):
  File "matlab_formatter.py", line 300, in <module>
    main()
  File "matlab_formatter.py", line 297, in main
    formatter.formatFile(sys.argv[1], start, end)
  File "matlab_formatter.py", line 251, in formatFile
    (offset, line) = self.formatLine(line)
  File "matlab_formatter.py", line 210, in formatLine
    step = self.istep.pop()
IndexError: pop from empty list
```
instead of expected result:
```matlab
function [foo1, foo2] = myFun(a, b, c)
```

**Comment by affenwiesel** [comment]
Fixed in the latest update
