### ISSUE TITLE
IndexError pop from empty list

### ISSUE THREAD

**Issue by bensampson5** [affenwiesel/matlab-formatter-vscode#61]
Ubuntu 18.04 LTS
Python 3.7.6
VSCode 1.46.1

Here's a code snippet that matlab-formatter v2.8.0 fails to format properly after trying to run Format Document (Ctrl+Shift+I).

```i = 1;
count = 0;
while i <= length(txt)
    if txt(i) == '{' || txt(i) == '['
        count = count + 1;
    elseif txt(i) == '}' || txt(i) == ']'
        count = count - 1;
        tabs = '';
        for j = 1:count
            tabs = [tabs, '  '];
        end
        txt = [txt(1:i-1), newline, tabs, txt(i:end)];
        i = i + length([newline, tabs]);
    end
    
    if txt(i) == ',' || txt(i) == '{' || txt(i) == '[' || ...
            txt(i) == '}' || txt(i) == ']'
        tabs = '';
        for j = 1:count
            tabs = [tabs, '  '];
        end
        txt = [txt(1:i), newline, tabs, txt(i+1:end)];
        i = i + length([newline, tabs]);
    end
    i = i + 1;
end
```

I get the following error back. I X'ed out my username for privacy.

formatting failed
Traceback (most recent call last):
  File "/home/XXX/.vscode/extensions/affenwiesel.matlab-formatter-2.8.0/formatter/matlab_formatter.py", line 317, in <module>
    main()
  File "/home/XXX/.vscode/extensions/affenwiesel.matlab-formatter-2.8.0/formatter/matlab_formatter.py", line 314, in main
    formatter.formatFile(sys.argv[1], start, end)
  File "/home/XXX/.vscode/extensions/affenwiesel.matlab-formatter-2.8.0/formatter/matlab_formatter.py", line 260, in formatFile
    (offset, line) = self.formatLine(line)
  File "/home/XXX/.vscode/extensions/affenwiesel.matlab-formatter-2.8.0/formatter/matlab_formatter.py", line 226, in formatLine
    step = self.istep.pop()
IndexError: pop from empty list

**Comment by affenwiesel** [comment]
The issue were the brackets inside the strings. I completely missed that ;).
Fixed in the latest update!
